plugins {
    id 'com.github.sherter.google-java-format' version '0.9'
}

apply plugin: 'java'

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:all"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
